features: deal -> contact management, list deals, corresponding cli changes
devflowinc/CLI-CRM pull request #55
Opened 2024-06-10 22:25 UTC by aaryanpunia

still working on it, lmk if there's something I should change before I finish this PR

2024-06-11 18:29 UTC, skeptrunedev requested changes

2024-06-11 18:29 UTC, skeptrunedev commented on actix-server/migrations/2024-06-10-180032_add_contact_deal_table/up.sql
> +	FOREIGN KEY ("contact_id") REFERENCES "contacts" ("id"),
Can you `CASCADE DELETE` these relations?

2024-06-11 18:32 UTC, skeptrunedev requested changes

2024-06-11 18:32 UTC, skeptrunedev commented on actix-server/src/handlers/contact_handler.rs
> +    ("offset" = i64, Query, description = "The offset to start from"),
```suggestion
    ("offset" = uuid, Query, description = "The offset to start from"),
```

When you offset by a `number` it doesn't use the index and is really slow. Not the best blog, but - https://geronimovelasco.medium.com/how-limit-and-offset-works-behind-the-scenes-in-postgresql-a09c2c063405

2024-06-11 18:45 UTC, skeptrunedev requested changes

2024-06-11 18:45 UTC, skeptrunedev commented on actix-server/src/operators/contact_operator.rs
> +        .load::<Contact>(&mut conn)
You need an `order_by` here.

2024-06-11 18:45 UTC, skeptrunedev commented on actix-server/src/operators/contact_operator.rs
> +        .load::<Contact>(&mut conn)
`.filter(contacts::columns::id.gt(offset)`

2024-06-11 18:45 UTC, skeptrunedev commented on actix-server/src/handlers/deal_handler.rs
> +#[serde(rename_all = "snake_case")]
```suggestion
```

I think this should be a different PR. Because if we're going to do it, we should do it to everything at once.

2024-06-11 18:47 UTC, skeptrunedev requested changes
1. Change pagination in `operator`'s to use the `id` column instead of raw numeric `offset`. Also need `order_by(id)`. 
2. Rename OpenAPI spec exposed struct's/enum's to match existing pattern

2024-06-11 18:59 UTC, drew-harris commented on actix-server/src/operators/contact_operator.rs
> +pub async fn get_contacts_by_deal_id(
nitpick but we should keep the consistent _query suffix

2024-06-11 18:59 UTC, drew-harris commented on actix-server/src/operators/contact_operator.rs
> +pub async fn get_contacts_by_org_id(
nitpick but we should keep the consistent _query suffix

2024-06-11 18:59 UTC, drew-harris commented on actix-server/src/operators/contact_operator.rs
> +pub async fn get_contacts_by_deal_id(
goes for other operator methods too, i dont wanna spam comment

2024-06-11 19:31 UTC, drew-harris commented
![image](https://github.com/devflowinc/CLI-CRM/assets/61394759/9bcf8009-9a42-4a47-acde-a05c29a3d029)
adding a contact to a deal fails silently

2024-06-11 19:33 UTC, drew-harris commented on actix-template-cli/src/commands/contacts.rs
> +            println!("Contact created successfully");
Would be nice to print the id here so that users can copy paste it into future commands instead of having to go through the list step.

2024-06-11 19:45 UTC, drew-harris commented
LGTM, except for the error handling in main (we still gotta figure out/agree on a standard, not blocking this) and my earlier comment

2024-06-13 23:18 UTC, skeptrunedev approved these changes

2024-06-13 23:20 UTC, merged